apiVersion: v1
kind: ConfigMap
metadata:
  name: codr-{{ .Release.Name }}-configmap
data:
  {{- include "getKafkaClusters" .Values | indent 2 }}
  AUTH_TYPE: "LOGIN_FORM"
  SPRING_SECURITY_USER_NAME: admin
  SPRING_SECURITY_USER_PASSWORD: password