apiVersion: v1
kind: ConfigMap
metadata:
  name: codr-{{ .Release.Name }}-configmap
data:
  {{- include "getKafkaClusters" .Values | indent 2 }}
  # AUTH_TYPE: "LOGIN_FORM"
  # SPRING_SECURITY_USER_NAME: {{ .Values.security.username }}
  # SPRING_SECURITY_USER_PASSWORD: {{ .Values.security.password }}