kind: Deployment
apiVersion: apps/v1
metadata:
  name: codr-{{ .Release.Name }}
  labels:
    app: codr-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codr-{{ .Release.Name }}
  template:
    metadata:
      name: codr-{{ .Release.Name }}
      labels:
        app: codr-{{ .Release.Name }}
    spec:
      containers:
        # RESTful API container
        - name: {{ .Release.Name }}
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - configMapRef:
                name: codr-{{ .Release.Name }}-configmap
          resources:
            limits:
              memory: 256Mi
              cpu: "0.5"
            requests:
              memory: 128Mi
              cpu: "0.2"
