apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: codr-kakfa-schema-registry
spec:
  replicas: 1
  serviceName: codr-kakfa-schema-registry
  selector:
    matchLabels:
      app: codr-kakfa-schema-registry
  template:
    metadata:
      labels:
        app: codr-kakfa-schema-registry
    spec:
      hostname: schema-registry
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi
            limits:
              cpu: "0.5"
              memory: 1Gi
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - configMapRef:
                name: codr-{{ .Release.Name }}-configmap
