apiVersion: v1
kind: Service
metadata:
  name: kafka-{{ .Release.Name }}
spec:
  selector:
    app: codr-kafka-{{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPart: 8081
  type: LoadBalancer